# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-25 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profiles/')),
                ('bio', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(max_length=245),
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Project'),
        ),
    ]
