# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20181226_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='awards.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
