# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Comment',
            new_name='comment',
        ),
    ]
