# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20181230_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Profile'),
        ),
    ]
